# This is a basic workflow to help you get started with Actions
name: React test project

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the predefined actions
      - name: Get the code.
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Runs a set of commands using the runners shell
      - name: Install dependencies.
        run: npm ci

      - name: Run the test cases.
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the code.
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies.
        run: npm ci

      - name: Build the project.
        run: npm run build

      - name: Deploy
        run: echo "Deplying..."
